// import type { Metadata } from 'next';
import type { Metadata } from 'next/dist/lib/metadata/types/metadata-interface';
import './globals.css';
import {
  ClerkProvider,
} from '@clerk/nextjs';
import { ThemeProvider } from '@/components/theme-provider'
import { Toaster } from '@/components/ui/toaster'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang='en' suppressHydrationWarning>
        <body className='bg-secondary'>
        <ThemeProvider
            attribute="class"
            defaultTheme="system">
          {/* <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn> */}
          {children}
          <Toaster/>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
